version: '3.8'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=2n^4xy$g*dffb&3^z+7z1w!+jht=#9m!o8)c4w#4&c=1$5(1)5
      - DATABASE_URL=postgres://user:password@db/mydb
    depends_on:
      - db
      - cerbos
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cerbos:
    image: ghcr.io/cerbos/cerbos:latest
    command: "server --config=/config/conf.yaml" 
    volumes:
      - ./cerbos/policies:/policies
      - ./cerbos/config/conf.yaml:/config/conf.yaml 
    ports:
      - "3592:3592"


volumes:
  postgres_data: