# Generated by Django 4.2.15 on 2024-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
            ],
        ),
    ]
